version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ../chat-app-api
      # Only the development stage from the 
      # Docker files
      target: development 

      # Mount our host dir to the docker container
      # Mount api directory (../chat-app-api) to (:) docker container
      # Which is (/mawalou14/src/app)
      # Reflect File changes from host to container
      volumes:
        - ../chat-app-api:/mawalou14/src/app
        - ../mawalou14/src/app/node_modules
      # RUN in debug mode: npm run start:Debug 
      # ---> Also start your vscode debugger
      # Run in dev mode: npm run start:dev
      command: npm run start:dev
      environment:
        NODE_ENV: development
        PORT: 3000
      ports:
        - 3000:3000
        - 9229:9229
